"""Job_Booster data models."""

from .api_models import (
    AnalysisData,
    AnalysisRequest,
    AnalysisResponse,
    CoverLetterData,
    CoverLetterRequest,
    CoverLetterResponse,
    ExperienceMatch,
    JobParseResponse,
    JobTextRequest,
    ResumeParseResponse,
    SkillMatch,
    TailoredResumeData,
    TailoredResumeRequest,
    TailoredResumeResponse,
)
from .base_model import BaseResponse, JobBoosterBase
from .job_model import (
    Benefit,
    CompanyInfo,
    JobPosting,
    Requirement,
    Responsibility,
)
from .resume_model import (
    Certification,
    ContactInfo,
    Education,
    Project,
    Resume,
    ResumeFormat,
    ResumeVersion,
    Skill,
    WorkExperience,
)

__all__ = [
    "JobBoosterBase",
    "BaseResponse",
    "Resume",
    "ResumeFormat",
    "ResumeVersion",
    "ContactInfo",
    "Education",
    "WorkExperience",
    "Project",
    "Skill",
    "Certification",
    "JobPosting",
    "CompanyInfo",
    "Requirement",
    "Responsibility",
    "Benefit",
    "ResumeParseResponse",
    "JobParseResponse",
    "JobTextRequest",
    "AnalysisRequest",
    "AnalysisData",
    "AnalysisResponse",
    "SkillMatch",
    "ExperienceMatch",
    "TailoredResumeRequest",
    "TailoredResumeData",
    "TailoredResumeResponse",
    "CoverLetterRequest",
    "CoverLetterData",
    "CoverLetterResponse",
]
